---
name: Build and Push Docker Container

on: 
  workflow_dispatch:
  pull_request: 
    branches: [ $default_branch ]
  push:

env:
  github_runner: ubuntu-latest
  container_name: gh-cli
  docker_file: ubuntu20.Dockerfile
  docker_tags: ghcr.io/gunnarwustl/gh-cli:ubuntu20

jobs: 
  diff_check:
    runs-on: ubuntu-latest
    steps:
      - name: Diff Check
        uses: ./.github/workflows/steps/diff-check.yaml
  
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push
        uses: ./.github/workflows/steps/docker-build.yaml
        with: 
          push_image_bool: true
